theme: jekyll-theme-minimal
title: TCC - Editor de Partituras para Percussão
description: Informações sobre a proposta de TCC de Felipe no IME-USP.
show_downloads: false
google_analytics: 
# As linhas abaixo "limpam" os links automáticos do GitHub
github:
  is_project_page: false
