remote_theme: pages-themes/minimal@v0.2.0
title: TCC MAC0500 - Sistema para Notação e Sincronização Áudio-Visual de Percussão
description: Informações sobre o projeto de TCC de Felipe Sousa dos Santos.
show_downloads: false
google_analytics: 
# As linhas abaixo "limpam" os links automáticos do GitHub
github:
  is_project_page: false
